---
title: 'pytorch tensors'
description: 'pytorch tensors'
author: 'janf'
date: '2023-09-09'
date-format: iso
categories: [notes]
toc: true
execute: 
  enabled: false
format:
  html:
    code-copy: true
draft: false
---

## What are Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of model, as well as the model's parameters. Tensors are similar to NumPy's arrays, expect that tensors can run on GPU or other hardware.

[PyTorch Tensor](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

[Introduction to PyTorch Tensors](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)

## Creating PyTorch Tensors

In [118]:
import torch
import math

### Factory Method to create Tensor
The simplest way to create a tensor is with the torch.empty() call:

In [119]:
x = torch.empty(3,4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[3.2007e-36, 0.0000e+00, 2.8482e-36, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
        [2.8872e-36, 0.0000e+00, 5.6052e-45, 0.0000e+00]])


- this creates a tensor using on of the numerous factory methods attached to the **torch** module.
- the tensor itself is 2-dimensional, having 3 rows and 4 columns.
- the type of the object returned is **torch.Tensor**, which is an alias for **torch.FloatTensor**, by default PyTorch tensors are 32-bit floating point numbers.
- there are some random-looking values in the tensor. The **torch.empty()** call allocates memory for the tensor, but does not initialize it with any values -  so what your're seeing is whatever was in memory at the time of allocation.

If you want to initialize the tensor with some vales. Common cases are all zeros, all ones, or random values. The torch module provides factory methods for alle of these:

In [120]:
# create a tensor full of zeros
zeros = torch.zeros(2,3)
print(zeros)

# create a tensor full of ones
ones = torch.ones(2,3)
print(ones)

# create a tensor full of random values
torch.manual_seed(1779)
random = torch.rand(2,3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3699, 0.5704, 0.4876],
        [0.3391, 0.1535, 0.0455]])


### Terminology about tensors and thier number of dimensions

- You will sometimes see a **1-dimensional tensor** called a **vector**.
- A **2-dimensional tensor** is often referred as a **matrix**.
- Anything with **more than two dimensions** is generally just called a **tensor**.

### Random Tensor and Seeding

Sometimes you want the same random values for reproducibility. Manually setting your random number generator's seed fixes the random outputs to get the same results.

In [121]:
torch.manual_seed(1729)
random1 = torch.rand(2,3)
print(random1)

random2 = torch.rand(2,3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2,3)
print(random3)

random4 = torch.rand(2,3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


What you should see above is that **random1** and **random3** carry identical values, as do **random2** and **random4**. Manually resetting the seed gives the same results when you compute the things again.

### Tensor Shapes

Often when you are performing operations on two or more tensors, they will need to be of the same shape - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the **torch.*_like()** methodes:

In [122]:
x = torch.empty(2,2,3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)


torch.Size([2, 2, 3])
tensor([[[2.8892e-36, 0.0000e+00, 2.7489e-36],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[2.9069e-36, 0.0000e+00, 2.7489e-36],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


The first new thing in the code cell above is the use of the **.shape** property on a tensor. This property contains a list of the extent of each dimension of a tensor - in our case, **x** is a three-dimensional tensor with shape 2x2x3. Then we created new tensor's with **.empty_like(), .zeros_like(), .ones_like(), .rand_like()** methods. With **.shape** we can verify that **x** has the same size as our new tensors.



### Create a Tensor with specific data directly

In [123]:
some_constants = torch.tensor([[3.141, 2.789], [1.234, 4.923]])
print(some_constants.shape)
print(some_constants)

some_intergers = torch.tensor((2,3,4,5,6,7,8,9,10,11))
print(some_intergers.shape)
print(some_intergers)

more_intergers = torch.tensor(((2,4,6), [3,6,9]))
print(more_intergers.shape)
print(more_intergers)

torch.Size([2, 2])
tensor([[3.1410, 2.7890],
        [1.2340, 4.9230]])
torch.Size([10])
tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([2, 3])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using **torch.tensor()** is the most straightforward way to create a tensor if your already have data in a Python tuple or list. Nesting will result in multi-dimensional tensor.

Note: **torch.tensor()** creates a copy of the data.

### Understanding Tensor Shapes



Consider tensor shapes as the number of lists that a dimension holds. For instance, a tensor shaped (4,4,2) will have four elements, which all contain 4 elements, which in turn have 2 elements.

1. The first holds 4 elements.
2. The second holds 4 elements.
3. The third dimension holds 2 elements.

![torch.Size([4,4,2"])](441.jpg)

In [124]:
tensor442 = torch.empty(4,4,2)
print(tensor442.shape)
print(tensor442)

torch.Size([4, 4, 2])
tensor([[[ 1.4934e-38,  0.0000e+00],
         [ 2.7444e-36,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 1.5835e-43,  0.0000e+00]],

        [[-1.2993e+10,  4.5653e-41],
         [ 2.7445e-36,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00]],

        [[ 9.1844e-41,  1.1551e-40],
         [ 1.1481e-41,  2.0739e-43],
         [ 8.9683e-44,  0.0000e+00],
         [ 6.7262e-44,  0.0000e+00]]])


### Data structures in tensors

In [125]:
# [x]
# ----------------------- 
# scalar
# 0D (zero dimension)
print('create tensor:')
d0 = torch.ones(1)
print(d0)

print('create tensor:')
d0 = torch.tensor([1.])
print(d0)

print('get value 1:')
print(d0[0])

print('shape:')
print(d0.shape)


create tensor:
tensor([1.])
create tensor:
tensor([1.])
get value 1:
tensor(1.)
shape:
torch.Size([1])


In [126]:
# [x]
# [x]
# [x]
# -----------------------
# vector
# 1D (one dimension)
print('create tensor:')
d1 = torch.ones(3)
print(d1)

print('create tensor:')
d1 = torch.tensor([1.,2.,3.])
print(d1)

print('get value 3:')
print(d1[2])

print('shape:')
print(d1.shape)

create tensor:
tensor([1., 1., 1.])
create tensor:
tensor([1., 2., 3.])
get value 3:
tensor(3.)
shape:
torch.Size([3])


In [127]:
# [x x x]
# [x x x]
# [x x x]
# -----------------------
# matrix
# 2D (two dimension)
print('create tensor:')
d2 = torch.ones(3,3)
print(d2)

print('create tensor:')
d2 = torch.tensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print(d2)

print('get value 4:')
print(d2[1,0])

print('shape:')
print(d2.shape)

create tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
create tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
get value 4:
tensor(4.)
shape:
torch.Size([3, 3])


In [128]:
# [x x x] [x x x] [x x x]
# [x x x] [x x x] [x x x]
# [x x x] [x x x] [x x x]
# -----------------------
# tensor
# 3D (3 dimension)

# TODO

In [129]:
# dimension > 3
# -----------------------
# tensor
# XD (x > 3 dimension)

# TODO

### Tensor Data Types

Setting the datatype of a tensor is possible a couple of ways:

In [130]:
a = torch.ones((2,3), dtype=torch.int16)
print(a)

b = torch.rand((2,3), dtype=torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


The simplest way to set underlying data type of a tensor is with an optional argument at creation time. At "a" we set **dtype=torch.int16**. Printing **a** shows that the data is 1 rather than 1. (1 int, 1. float)

Another thing to notice by printing out a tensor it also shows the specified dtype.

Another way to set the datatype is with the **.to()** method. In the cell above, we create a random floating point tensor **b** and den converted b to a 32-bit integer in **c**.

PyTorch datatypes:

- torch.bool
- torch.int8
- torch.uint8
- torch.int16
- torch.int32
- torch.int64
- torch.half
- torch.float
- torch.double
- torch.bfloat

## Math & Logic with Tensors

Basic arithmetic with tensors and how tensor interact with simple scalars:

In [131]:
ones = torch.zeros(2,2) + 1
twos = torch.ones(2,2) * 2
threes = (torch.ones(2,2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


Arithmetic operations between tensors and scalars, such as addition, subtraction, multiplication, division, and exponentiation are distributed over every element of the tensor.

Operation between tow tensors also behave like you'd intuitively expect:

In [132]:
powers2 = twos ** torch.tensor([[1,2], [3,4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


It's important to note that all of the tensors in the previous code cell were of identical shape. What happens when we try to perform a binary operation on tensor if dissimilar shape?

In [133]:
# The following throws a run-time error. This is intentional.

a = torch.rand(2,3)
b = torch.rand(3,2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In general case, you cannot operate on tensors of different shape this way,even in a case like the call above, where the tensor have identical number of elements.

### In Brief: Tensor Broadcasting

The exception to the same-shape rule is tensor broadcasting. Here's an example:

In [ ]:
import torch

rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4)*2)

print(rand)
print(doubled)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


How is it we get to multiply a 2x4 tensor by a 1x4 tensor?

Broadcasting is a way to perform an operation between tensors that have similarities in their shapes. In the example above, the one-row, four-column tensor is multiplied by both rows of the two-row, four-column tensor.

![Pytorch Broadcasting](broadcasting.jpg)

This is an important operation in Deep Learning. The common example is multiplying a tensor of learning weights by a batch of input tensors, applying the operation to each instance in the batch separately, and returning a tensor of identical shape - just like our (2,4) * (1,4) example above returned a tensor of shape (2,4).

The rules of broadcasting are:

- Each tensor must have at least one dimension - no empty tensors.
- Comparing the dimension sizes of the tow tensors, going from last to first:
    - Each dimension must be equal of
    - One of the dimension must be of size 1, or
    - Dimension does not exist in one of the tensors

Tensors of identical shape, of course are trivially "broadcastable", as you saw earlier.

Here are some examples of situation that honor the above rules and allow broadcasting:

In [ ]:
a = torch.ones(     4,  3,  2)
print(a)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [ ]:
b = a * torch.rand(     3,  2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.0381, 0.2138],
         [0.5395, 0.3686],
         [0.4007, 0.7220]],

        [[0.0381, 0.2138],
         [0.5395, 0.3686],
         [0.4007, 0.7220]],

        [[0.0381, 0.2138],
         [0.5395, 0.3686],
         [0.4007, 0.7220]],

        [[0.0381, 0.2138],
         [0.5395, 0.3686],
         [0.4007, 0.7220]]])


In [ ]:
c = a * torch.rand(     3,  1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.8217, 0.8217],
         [0.2612, 0.2612],
         [0.7375, 0.7375]],

        [[0.8217, 0.8217],
         [0.2612, 0.2612],
         [0.7375, 0.7375]],

        [[0.8217, 0.8217],
         [0.2612, 0.2612],
         [0.7375, 0.7375]],

        [[0.8217, 0.8217],
         [0.2612, 0.2612],
         [0.7375, 0.7375]]])


In [ ]:
d = a * torch.rand(     1,  2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]],

        [[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]],

        [[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]],

        [[0.8328, 0.8444],
         [0.8328, 0.8444],
         [0.8328, 0.8444]]])


Look closely at the values of each tensor above:

- The multiplication operation that created **b** was broadcast over every 'layer' of **a**.
- For **c**, the operation was broadcast over ever layer and row of **a** - every 3-element column is identical.
- For **d**, we switched it around - now every row is identical, across layers and columns.

One example where broadcasting will fail:

In [ ]:
a = torch.ones(     4,  3,  2)

b = a * torch.rand(     4,  3)  # dimension must match last-to-first

c = a * torch.rand(     2,  3)  # both 3rd & 2nd dims different

d = a * torch.rand(0,)          # cant broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

## Copying Tensors

## Moving to GPU

## Manipulating Tensors Shpares

## Pytorch-Numpy Bridge
