---
title: 'pytorch tensor cheatsheet'
description: 'pytorch tensor cheatsheet'
author: 'janf'
date: '2023-09-09'
date-format: iso
categories: [cheatsheet]
toc: true
execute: 
  enabled: false
format:
  html:
    code-copy: true
draft: false
---

## What are Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of model, as well as the model's parameters. Tensors are similar to NumPy's arrays, expect that tensors can run on GPU or other hardware.

[PyTorch Tensor](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

[Introduction to PyTorch Tensors](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)

In [39]:
#| echo: false
import math

## Import torch

In [40]:
import torch

## Creating Tensors

Ways to create a tensor.

### Factory Method

Creating an empty tensor. <b>torch.empty()</b>

In [41]:
# creating a tensor with 2-dimensions, 3 rows and 4 columns.
x = torch.empty(3,4)
# by default tenors are 32-bit gloating point numbers.
# torch.empty() allocates memory for the tensor but does not initialize it with any values
print(x)

tensor([[1.5766e-19, 1.0256e-08, 2.5783e-09, 3.0441e+12],
        [4.3353e-08, 1.7188e-04, 6.7510e-07, 1.2611e+16],
        [2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31]])


Creating a tensor full of zeros. <b>torch.zeros()</b>

In [42]:
# creating a tensor with 2-dimensions, 2 rows and 3 columns.
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


Creating a tensor full of ones. <b>torch.ones()</b>

In [43]:
# creating a tensor with 2-dimensions, 3 rows and 1 column.
x = torch.ones(3,1)
print(x)

tensor([[1.],
        [1.],
        [1.]])


Creating a tenor full of random values. <b>torch.rand()</b>

In [44]:
torch.manual_seed(187)
# creating a tensor with 2-dimension, 2 rows and 3 columns.
random = torch.rand(2,3)
print(random)

tensor([[0.5305, 0.9925, 0.7754],
        [0.9989, 0.3047, 0.9887]])


### Creating a tensor with specific data directly

<b>torch.tensor()</b> is the way to create a tenors if you have a Python tuple or list. Is creates a copy of the data as tensor.

In [45]:
x = torch.tensor(([1,2,3],[4,5,6]))
print(x.shape)
print(x)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### Random tensor and seeding

<b>torch.manual_seed()</b> sets the random seed to fixes the random outputs.

<b>torch.rand()</b> creates a random tensor.

In [46]:
torch.manual_seed(187)
random = torch.rand(5,5)
print(random)

tensor([[0.5305, 0.9925, 0.7754, 0.9989, 0.3047],
        [0.9887, 0.3299, 0.2694, 0.5281, 0.8815],
        [0.5275, 0.7802, 0.9964, 0.1060, 0.5047],
        [0.6960, 0.1014, 0.8651, 0.9504, 0.7015],
        [0.2917, 0.7787, 0.3808, 0.2624, 0.6519]])


### Creating tensor with the shape like

Creating a tensor having the same number dimensions and the same number of cells in each dimension.
- <b>torch.empty_like()</b>
- <b>torch.zeros_like()</b>
- <b>torch.ones_like()</b>
- <b>torch.rand_like()</b>

In [47]:
x = torch.empty(2,2,3)
print(x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x)

tensor([[[0.0000e+00, 6.8664e-44, 2.7002e-06],
         [2.6965e+23, 3.3429e+21, 1.0489e-08]],

        [[1.6505e-07, 1.7664e-04, 4.1532e-08],
         [5.3928e-05, 1.6597e-07, 5.3130e-08]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


### Terminology about tensors and thier number of dimensions

- 0-dimensional tensor is called a scalar
- 1-dimensional tensor is called a vector
- 2-dimensional tensor is called a matrix
- 3-dimensional or more tensor is called a tensor

In [48]:
d0 = torch.ones(1)
print('scalar (0-dim)')
print(d0)
print('\n')

d1 = torch.ones(1,4)
print('vector 1-dim')
print(d1)
print('\n')


d2 = torch.ones(3,3)
print('matrix 2-dim')
print(d2)
print('\n')

d3 = torch.ones(4,4,4)
print('tensor 3-dim or more')
print(d3)

scalar (0-dim)
tensor([1.])


vector 1-dim
tensor([[1., 1., 1., 1.]])


matrix 2-dim
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor 3-dim or more
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


<b>.shape</b> property gives list of the extant of each dimension 

In [49]:
x = torch.zeros(2,1)
x.shape

torch.Size([2, 1])

### Tensor data types

One way to set the data type of a tensor is with an optional argument at creation.

You can see the specified dtype by printing the tensor.

In [50]:
a = torch.ones((2,3), dtype=torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


Another way to set the datatype is with the **.to()** method. It converts a float64 and creates a int32 tensor.

In [51]:
a = torch.ones((2,3), dtype=torch.float64)
print(a)

b = a.to(torch.int32)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


PyTorch datatypes:

- torch.bool
- torch.int8
- torch.uint8
- torch.int16
- torch.int32
- torch.int64
- torch.half
- torch.float
- torch.double
- torch.bfloat

## Math & Logic

Basic arithmetic with tensors.

In [52]:
twos = torch.ones(2,2) * 2
print(twos)

tensor([[2., 2.],
        [2., 2.]])


Arithmetic operations between tensors and scalars, such as addition, subtraction, multiplication, division, and exponentiation are distributed over every element of the tensor.

Operation between tow tensors also behave intuitively:

In [53]:
ones = torch.ones(2,2)
print(ones + twos)

tensor([[3., 3.],
        [3., 3.]])


Tensors of dissimilar shape will throw a run-time error when calculated via binary operation.

In [54]:
# The following throws a run-time error. This is intentional.
a = torch.rand(2,3)
b = torch.rand(3,4)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

More math-operations:

[More Pytorch Math-Operations](https://pytorch.org/docs/stable/torch.html#math-operations)

## Tensor Broadcasting

The exception to the same-shape rule is tensor broadcasting.

In [ ]:
rand = torch.rand(2,4)
doubled = rand * (torch.ones(1,4)*2)

print(rand)
print(doubled)

tensor([[0.6098, 0.3175, 0.3386, 0.4934],
        [0.9187, 0.8510, 0.7339, 0.3254]])
tensor([[1.2195, 0.6349, 0.6772, 0.9867],
        [1.8375, 1.7020, 1.4677, 0.6508]])


How is it we get to multiply a 2x4 tensor by a 1x4 tensor?

Broadcasting is a way to perform an operation between tensors that have similarities in their shapes. In the example above, the one-row, four-column tensor is multiplied by both rows of the two-row, four-column tensor.

broadcasting examples:

![Pytorch Broadcasting](broadcasting.jpg)

This is an important operation in Deep Learning. The common example is multiplying a tensor of learning weights by a batch of input tensors, applying the operation to each instance in the batch separately, and returning a tensor of identical shape - just like (2,4) * (1,4) example above returned a tensor of shape (2,4).

The rules of broadcasting are:

- Each tensor must have at least one dimension - no empty tensors.
- Comparing the dimension sizes of the two tensors, going form last to first:
    - Each dimension must be equal of
    - One of the dimension must be of size 1, or
    - Dimension does not exist in one of the tensors

Tensors of identical shape, of course are trivially "broadcastable", as you saw earlier.

Here are some examples of situation that honor the above rules and allow broadcasting:

In [ ]:
a = torch.ones(4,3,2)
print(a)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [ ]:
b = a * torch.rand(3,2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

tensor([[[0.6381, 0.9161],
         [0.5682, 0.7014],
         [0.7000, 0.8772]],

        [[0.6381, 0.9161],
         [0.5682, 0.7014],
         [0.7000, 0.8772]],

        [[0.6381, 0.9161],
         [0.5682, 0.7014],
         [0.7000, 0.8772]],

        [[0.6381, 0.9161],
         [0.5682, 0.7014],
         [0.7000, 0.8772]]])


In [ ]:
d = a * torch.rand(1,2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.6071, 0.9969],
         [0.6071, 0.9969],
         [0.6071, 0.9969]],

        [[0.6071, 0.9969],
         [0.6071, 0.9969],
         [0.6071, 0.9969]],

        [[0.6071, 0.9969],
         [0.6071, 0.9969],
         [0.6071, 0.9969]],

        [[0.6071, 0.9969],
         [0.6071, 0.9969],
         [0.6071, 0.9969]]])


In [ ]:
a = torch.ones(     4,  3,  2)

b = a * torch.rand(     4,  3)  # dimension must match last-to-first

c = a * torch.rand(     2,  3)  # both 3rd & 2nd dims different

d = a * torch.rand(0,)          # cant broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

### Altering Tensors in Place

Most binary operations on tensors will return a third, new tensor. When we say c = a * b (where a and b are tensors), the new tensor c will occupy a region of memory distinct from the other tensors.

There are times, though, that you may whish to alter a tensor in place - for example. if you're doing an element-wise computation where you can discard intermediate value. For this, most of the math function have a version with an underscore(_) that will alter a tensor in place.


In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))     # this operation creates a new tensor in memory
print(a)                # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))    # note the underscore
print(b)                # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


For arithmetic operations, here are function that behave similar:

In [ ]:
a = torch.ones(2,2)
b = torch.rand(2,2)

print('Before: ')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before: 
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4583, 0.6130],
        [0.6209, 0.9512]])

After adding:
tensor([[1.4583, 1.6130],
        [1.6209, 1.9512]])
tensor([[1.4583, 1.6130],
        [1.6209, 1.9512]])
tensor([[0.4583, 0.6130],
        [0.6209, 0.9512]])

After multiplying
tensor([[0.2100, 0.3757],
        [0.3856, 0.9048]])
tensor([[0.2100, 0.3757],
        [0.3856, 0.9048]])


Note that these in-place arithmetic functions are methods an the torch.Tensor object, not attached to the torch module like many other functions (e.g. torch.sin()). As you can see from a.add_(b), the calling tensor is the one that gets changed in place.

## Copying Tensors

As with any object in Python, assigning a tensor to a variable makes the variable a label of the tensor, and does not copy it. For example.

In [ ]:
a = torch.ones(2,2)
b = a

a[0][1] = 561   # we change a ...
print(b)        # and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


But what is if you want a separated copy of the data to work on? The clone() method is there for you:

In [ ]:
a = torch.ones(2,2)
b = a.clone()

assert b is not a       # differen objects in  memory ...
print(torch.eq(a,b))    # ... but still with the same contents

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


There is an important thing to be aware of when using clone(). If your source tensor has autograd enabled then so will the clone. This will be covered more deeply in the video on autograd, but if you want the light version of the details, continue on.

## Moving to GPU

To check whether a GPU is available we can use <b>torch.cuda.is_available()</b>

In [ ]:
if torch.cuda.is_available():
    print('We have GPU!')
else:
    print('Sorry, CPU only')

We have GPU!


By default new tensors are created on the CPU. You have to specify an optional device argument to use the tensor on a GPU.

As an coding practice, specifying our devices everywhere with string constants is pretty fragile. You can create a device handle to pass it to you tensors.

In [ ]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')

print('Device: {}'.format(my_device))

x = torch.rand(2,2, device=my_device)
print(x)

Device: cuda
tensor([[0.2694, 0.5133],
        [0.4625, 0.0572]], device='cuda:0')


With <b>.to()</b> you can move a tensor from CPU to a GPU or vise versa.

In [ ]:
y = torch.rand(2,2)
y = y.to(my_device)

Tensors must be on the same device.

In [ ]:
x = torch.rand(2,2, device='cpu')
y = torch.rand(2,2, device='cuda')

z = x + y # exception will be thrown

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

## Manipulating Tensor Shapes

### Changing Shape by Squwwzing And Unsqueezing
<b>unsqueeze()</b> method adds a dimension of extent 1. unsqueesze(1) adds it as a new zeroth dimension.

In [ ]:
a = torch.rand(2,266,266)
b = a.unsqueeze(0)
print(a.shape)
print(b.shape)

torch.Size([2, 266, 266])
torch.Size([1, 2, 266, 266])


When we <b>squeeze()</b> a tensor, the dimensions of size 1 are removed. The elements of the original tensor are arranged with the remaining dimensions. For example, if the input tensor is of shape: (m×1×n×1) then the output tensor after squeeze will be of shape: (m×n).

In [ ]:
a = torch.rand(2,2)
print(a)
print(a.shape)

b = a.squeeze()
print(b)
print(b.shape)

c = torch.rand(1,20)
print(c)
print(c.shape)

d = c.squeeze()
print(d)
print(d.shape)

tensor([[0.5690, 0.0415],
        [0.1794, 0.7428]])
torch.Size([2, 2])
tensor([[0.5690, 0.0415],
        [0.1794, 0.7428]])
torch.Size([2, 2])
tensor([[0.1640, 0.1609, 0.6381, 0.9161, 0.5682, 0.7014, 0.7000, 0.8772, 0.6071,
         0.9969, 0.1627, 0.6761, 0.0416, 0.7503, 0.2614, 0.9380, 0.2171, 0.8036,
         0.7253, 0.2340]])
torch.Size([1, 20])
tensor([0.1640, 0.1609, 0.6381, 0.9161, 0.5682, 0.7014, 0.7000, 0.8772, 0.6071,
        0.9969, 0.1627, 0.6761, 0.0416, 0.7503, 0.2614, 0.9380, 0.2171, 0.8036,
        0.7253, 0.2340])
torch.Size([20])


### Reshaping a Tensor without changing the rank

Changing a tensor without changing the rank.

In [ ]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
print(t)

d = t.reshape([1,12])
print(d)

d = t.reshape([2,6])
print(d)


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])


Using <b>reshape()</b> we can specify the row x column shape that we are seeking. All of the shapes have to account for the number of elements in the tensor.

### Flatten a Tensor

A flatten operation on a tensor reshapes the tensor to have a shape that is equal to the number of elements contained in the tensor. This is the same thing as a 1d-array of elements.

In [ ]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
print(t.shape)

d = t.flatten()
print(d)
print(d.shape)

torch.Size([3, 4])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


## Pytorch-Numpy Bridge

In [ ]:
import numpy as np

numpy_array = np.ones((2,3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch creates a tensor of the same shape and containing the same data as the NumPy array, going so far as to keep NumPys default 64bit float data type. The conversion can also go the other way:

In [ ]:
pytorch_rand = torch.rand(2,3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.1050, 0.5877, 0.4583],
        [0.6130, 0.6209, 0.9512]])
[[0.10500968 0.5877479  0.4582944 ]
 [0.61297506 0.62093675 0.9512319 ]]


It is important to know that these converted objects are using the same underlying memory as thier source objects, meaning that changes to one are reflected in the other:

In [ ]:
numpy_array[1,1] = 23
print(pytorch_tensor)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
