---
title: 'pytorch tensor cheatsheet'
description: 'pytorch tensor cheatsheet'
author: 'janf'
date: '2023-09-09'
date-format: iso
categories: [cheatsheet]
toc: true
execute: 
  enabled: false
format:
  html:
    code-copy: true
draft: false
---

## What are Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of model, as well as the model's parameters. Tensors are similar to NumPy's arrays, expect that tensors can run on GPU or other hardware.

[PyTorch Tensor](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

[Introduction to PyTorch Tensors](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)

In [24]:
#| echo: false
import math

## Import torch

In [25]:
import torch

## Creating Tensors

Ways to create a tensor.

### Factory Method

Creating an empty tensor. <b>torch.empty()</b>

In [26]:
# creating a tensor with 2-dimensions, 3 rows and 4 columns.
x = torch.empty(3,4)
# by default tenors are 32-bit gloating point numbers.
# torch.empty() allocates memory for the tensor but does not initialize it with any values
print(x)

tensor([[1.1079e-35, 0.0000e+00, 3.6730e-36, 0.0000e+00],
        [1.5192e+13, 4.5656e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


Creating a tensor full of zeros. <b>torch.zeros()</b>

In [27]:
# creating a tensor with 2-dimensions, 2 rows and 3 columns.
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


Creating a tensor full of ones. <b>torch.ones()</b>

In [28]:
# creating a tensor with 2-dimensions, 3 rows and 1 column.
x = torch.ones(3,1)
print(x)

tensor([[1.],
        [1.],
        [1.]])


Creating a tenor full of random values. <b>torch.rand()</b>

In [29]:
torch.manual_seed(187)
# creating a tensor with 2-dimension, 2 rows and 3 columns.
random = torch.rand(2,3)
print(random)

tensor([[0.5305, 0.9925, 0.7754],
        [0.9989, 0.3047, 0.9887]])


### Creating a tensor with specific data directly

<b>torch.tensor()</b> is the way to create a tenors if you have a Python tuple or list. Is creates a copy of the data as tensor.

In [30]:
x = torch.tensor(([1,2,3],[4,5,6]))
print(x.shape)
print(x)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


### Random tensor and seeding

<b>torch.manual_seed()</b> sets the random seed to fixes the random outputs.

<b>torch.rand()</b> creates a random tensor.

In [32]:
torch.manual_seed(187)
random = torch.rand(5,5)
print(random)

tensor([[0.5305, 0.9925, 0.7754, 0.9989, 0.3047],
        [0.9887, 0.3299, 0.2694, 0.5281, 0.8815],
        [0.5275, 0.7802, 0.9964, 0.1060, 0.5047],
        [0.6960, 0.1014, 0.8651, 0.9504, 0.7015],
        [0.2917, 0.7787, 0.3808, 0.2624, 0.6519]])


### Creating tensor with the shape like

Creating a tensor having the same number dimensions and the same number of cells in each dimension.
- <b>torch.empty_like()</b>
- <b>torch.zeros_like()</b>
- <b>torch.ones_like()</b>
- <b>torch.rand_like()</b>

In [35]:
x = torch.empty(2,2,3)
print(x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x)

tensor([[[4.8634e-34, 4.5657e-41, 1.1022e-35],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


### Terminology about tensors and thier number of dimensions

- 0-dimensional tensor is called a scalar
- 1-dimensional tensor is called a vector
- 2-dimensional tensor is called a matrix
- 3-dimensional or more tensor is called a tensor

In [54]:
d0 = torch.ones(1)
print('scalar (0-dim)')
print(d0)
print('\n')

d1 = torch.ones(1,4)
print('vector 1-dim')
print(d1)
print('\n')


d2 = torch.ones(3,3)
print('matrix 2-dim')
print(d2)
print('\n')

d3 = torch.ones(4,4,4)
print('tensor 3-dim or more')
print(d3)

scalar (0-dim)
tensor([1.])
torch.Size([1])


vector 1-dim
tensor([[1., 1., 1., 1.]])


matrix 2-dim
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor 3-dim or more
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


<b>.shape</b> property gives list of the extant of each dimension 

In [55]:
x = torch.zeros(2,1)
x.shape

torch.Size([2, 1])

### Tensor data types

In [ ]:
a = torch.ones()